### ISSUE TITLE
Excel outputs blow up if document length > 131072

### ISSUE THREAD

**Issue by jonuwz** [jberger/Mojolicious-Plugin-ReplyTable#3]
Hi.

Mojo::Asset::Memory throws a substring out of range at line 45 for larger documents. This produces a corrupt xls or xlsx document.

Is it safe to use substr with binary data like this ?

At first I thought it was binmode related ( the Spreadsheet::XLSX readme says you should set this when writing to scalars ), but increasing the default max value in Mojo::Asset::Memory::get_chunk fixes the problem

**Comment by jberger** [comment]
That sounds very strange. I don't use get_chunk directly and I can't change the default value. Do you have some proposed fix?

**Comment by jberger** [comment]
From IRC discussion we tried the following

```
perl -Mojo -E 'Mojo::Asset::Memory->new->add_chunk("x" x 131073)->get_chunk'
```

And it seems to work as expected. I'm going to close for now but will reopen if you can supply more detail and especially if you can supply a test case.
