### ISSUE TITLE
"squish" is not exported by the Mojo::Util module

### ISSUE THREAD

**Issue by eserte** [jberger/Mojolicious-Plugin-ReplyTable#4]
Probably another problem caused by Mojolicious 7.0. Sample report:
http://www.cpantesters.org/cpan/report/517bf904-4e40-11e6-9c90-eb5010d7a009

**Comment by eserte** [comment]
-> https://metacpan.org/source/SRI/Mojolicious-7.0/Changes#L7

**Comment by jberger** [comment]
Thanks @eserte this is now fixed by https://github.com/jberger/Mojolicious-Plugin-ReplyTable/commit/4f45dc2b6ca550631d009f9c024cdcc668d575df

**Comment by eserte** [comment]
There's still something squish-related in 0.06:

```
Output from './Build test':

Wide character in method with known name at t/basic.t line 138.
Can't locate object method "squish" via package "head1  head2  head3
r1c1   r1c2   r1c3
r2c1   r2c2â  r2c3
" (perhaps you forgot to load "head1  head2  head3
r1c1   r1c2   r1c3
r2c1   r2c2â  r2c3
"?) at t/basic.t line 138.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 46.
t/basic.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 46 subtests passed 
```

**Comment by jberger** [comment]
ah drat, it is in a skip block that clearly I didn't enter. oops. thanks, will fix

**Comment by jberger** [comment]
ok lets try that again, fixed in https://github.com/jberger/Mojolicious-Plugin-ReplyTable/commit/edc0b81b6071d586febb8e510afda94bd203f4d5 (and tested with all the optional deps this time). Thanks again!
